model:
  base_learning_rate: 0.0001
  params:
    channels: 4
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
    cond_stage_key: txt
    cond_stage_trainable: false
    conditioning_key: crossattn
    first_stage_config:
      params:
        ddconfig:
          attn_resolutions: []
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 4
          double_z: true
          dropout: 0
          in_channels: 3
          num_res_blocks: 2
          out_ch: 3
          resolution: 1024  # SDXL's higher resolution
          z_channels: 4
        embed_dim: 4
        lossconfig:
          target: torch.nn.Identity
      target: ldm.models.sige_autoencoder.SIGEAutoencoderXL
    first_stage_key: jpg
    linear_end: 0.0120
    linear_start: 0.00085
    log_every_t: 200
    num_timesteps_cond: 1
    scale_factor: 0.18215
    scheduler_config:
      params:
        cycle_lengths: [10000000000000]
        f_max: [1.0]
        f_min: [1.0]
        f_start: [1.e-6]
        warm_up_steps: [10000]
      target: ldm.lr_scheduler.LambdaLinearScheduler
    timesteps: 1000
    unet_config:
      params:
        attention_resolutions: [32, 16, 8, 4]
        channel_mult: [1, 2, 4, 8]
        context_dim: 1024  # SDXL-specific
        image_size: 1024  # Higher resolution
        in_channels: 4
        legacy: false
        model_channels: 320
        num_heads: 16
        num_res_blocks: 2
        out_channels: 4
        transformer_depth: 2
        use_checkpoint: false
        use_spatial_transformer: true
      target: ldm.modules.diffusionmodules.sige_sdxl.SIGEUNetXL
